# -*- coding: utf-8 -*-
"""manager_of_projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rkzaOZoLDX4d17uAyjWxkl-mPN4mgR-
"""

#создание заметок
def create(notes):
  print('Введите текст для заметки:')
  notes.append(input())
  print('Заметка добавлена')
  return notes

def delete(notes):
  show(notes)
  print('Введите номер заметки, которую надо удалить:')
  index = int(input())
  if 0 <= index < len(notes):
    del notes[index]
    print("Заметка удалена.")
  else:
    print("Неверный номер заметки.")
  return notes

def search(notes):
  print('Введите заметку(ключевое слово) для поиска:')
  found_notes = [note for note in notes if input() in note]
  if not found_notes:
    print("Заметка не найдена.")
  else:
    print("Найденная заметка:")
    for i, note in enumerate(found_notes):
      print(f"{i + 1}. {note}")

def close():
  print('До свидания!')
  exit()

def show(notes):
  if not notes:
    print("Нет доступных заметок.")
  else:
    print("Ваши заметки:")
    for i, note in enumerate(notes):
      print(f"{i + 1}. {note}")

#интерфейс
def interface():
  with open('memory.txt', "r+") as f:
    notes = [line.strip() for line in f]
  print('Здравствуй, пользователь! Это менеджер твоих заметок.')
  while True:
    print('''Вот список доступных команд:
    1) создать заметку
    2) удалить заметку
    3) поиск заметки
    4) закрыть заметку
    5) показать заметку
    Введите номер выбранной команды:''')
    answer = input()
    match answer:
      case '1':
        create(notes)
      case '2':
        delete(notes)
      case '3':
        search(notes)
      case '4':
        close()
      case '5':
        show(notes)
      case _:
        print('Введены некорректные данные')
        continue